packages:
  # specify a package in a direct subdir of the root
  - 'playground'
  # all packages in direct subdirs of packages/
  - 'packages/*'

# resolutions:
#   packages/*: 'link:./packages/*/src'
